### ISSUE TITLE
Clarify the use of flags in README

### ISSUE THREAD

**Issue by bommox** [oliver006/redis_exporter#127]
Hi, 

We had a lot of trial-error to get this working in a kubernetes cluster.
The point was all flags must be written with ONE dash "-", like "-check-keys","-debug" etc. 

Please update README.md with an example of running with flags.

Thanks

**Comment by oliver006** [comment]
Thanks Jorge, sorry to hear it took you a while to figure out how to use the flags. I agree, the documentation could be better and include some example cases that show the use of the flags. If you have a moment to open a PR with some helpful examples that'd be great. Otherwise, I'll put it on the todo list and hope to get to it in the near future.

**Comment by jonathan-kosgei** [comment]
How do you chain flags? When I try to do this like `-redis.addr=redis://localhost:6379 -redis.password=test` It shows `redis.password` as a host?

**Comment by oliver006** [comment]
Just tried with the latest version of redis_exporter and Go1.9 - worked just fine.

I ran `./redis_exporter -redis.addr=localhost:6379 -redis.password=test` and it picked up the password as expected.

What version of redis_exporter and Go are you running and what's the exact command?
