### ISSUE TITLE
Stop using KEYS?

### ISSUE THREAD

**Issue by Tinche** [oliver006/redis_exporter#145]
Hi,

I've deployed this to monitor our production Redis. Thanks for writing it!

However, I've noticed you're using the KEYS command for the extra checkKeys. This is showing up in our slowlog and killing our Redis, basically (a single 'KEYS default:queue' takes 280 milliseconds since we have a lot of keys).

The docs for KEYS (https://redis.io/commands/keys) are explicit about this too: KEYS is O(n), don't use KEYS in production. 

Why not just do a TYPE against the key and then pick the proper length command based on that?

**Comment by oliver006** [comment]
Using `TYPE` is a neat idea, thanks for the suggestion.

I don't think it'd take much to implement, just cal `TYPE` and then a switch statement. I'm a little slammed with work right now and probably won't get to it until next week or so but a PR would be appreciated if you have time.

**Comment by Tinche** [comment]
I can put something together over the next few days!

**Comment by oliver006** [comment]
That'd be great!

**Comment by jstultz** [comment]
It's not clear to me how use of KEYS is related to the identification of the type of the key; it would certainly be nice to use TYPE to avoid having to try a number of different length commands, but it seems like what KEYS is doing in this code is to support the ability to check a key _pattern_; though that behavior is not documented. If that behavior is not documented because it's not needed or desired, it seems you could instead just remove the call to KEYS and just make calls with the user provided keys rather than generating `obtainedKeys`. Of course, if specifying a key pattern _is_ desired, then I don't see how using `TYPE` would avoid that, and I also don't see how to support that functionality without using `KEYS`. The two things seem orthogonal to me, unless I'm missing something.

**Comment by jstultz** [comment]
I see now that this is already mentioned in the related PR https://github.com/oliver006/redis_exporter/pull/149 ; thanks @Tinche

**Comment by oliver006** [comment]
Closing, this has been addressed via #172
