### ISSUE TITLE
How to monitor sentinel in the lastest version 1.0.0

### ISSUE THREAD

**Issue by antz-H** [oliver006/redis_exporter#268]
The firstly  I use the 1.0.0

Then  in the prometheus.yml  ,
...
- job_name: 'redis_138'
    static_configs:
       - targets: 
         - redis://192.168.27.138:6001
         - redis://192.168.27.138:6002
         - redis://192.168.27.138:6003
         - redis://192.168.27.138:6004
         - redis://192.168.27.138:6005
         - redis://192.168.27.138:6006
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.27.138:9121
...

6001、6002、6003 is redis
6004、6005、6006 is sentinel

redis is ok ，but  sentinel has any problem ；

i try  get  http://192.168.27.138:9121/scrape?target=redis://192.168.27.138:6005
![image](https://user-images.githubusercontent.com/43114886/58863239-0b7ec180-86e5-11e9-8b51-091bf4030789.png)

so, I want to know  how to config  the sentinel

**Comment by oliver006** [comment]
I'm not familiar with redis-sentinel beyond the basic idea of what it does so I can't really say if the exporter would work for monitoring redis-sentinel.
But my hunch is that it won't work out of the box. Or sat least not be very useful, there are definitely no sentinel-specific metrics being collected right now.

From reading the redis-sentinel docs I have a question though: the ports you use for sentinel (e.g. 6006) - are that the ports that correspondent to the default port sentinel port 26379 ? Because in that case the exporter should at least be able to connect to your sentinel processes.
