### ISSUE TITLE
An exporter should only monitor one host

### ISSUE THREAD

**Issue by brian-brazil** [oliver006/redis_exporter#32]
I noticed that the redis exporter has the ability to scrape multiple redis servers, and adds a `addr` label that partially duplicates the `instance` label. Per https://prometheus.io/docs/instrumenting/writing_exporters/#deployment there should be a 1-to-1 mapping between exporters and application instances.

**Comment by oliver006** [comment]
Some folks use the exporter to monitor e.g.  an external Azure Redis instance and I'd like to keep that as an option. 
I'm also not sure I understand what the actual problem is - the addional `addr` label? 

What is your suggestion to address this? 

Maybe drop/not add the `addr` label when no explicit redis instance address was provided?

**Comment by brian-brazil** [comment]
> Some folks use the exporter to monitor e.g. an external Azure Redis instance and I'd like to keep that as an option.

What I'm suggesting doesn't preclude that.

> I'm also not sure I understand what the actual problem is - the addional addr label?

The `addr` label, and that you allow monitoring more than one redis from one exporter.

**Comment by oliver006** [comment]
Ok, I see. Well, I like (and use) the ability to monitor more than one Redis instance and it doesn't really cause any harm or trouble so I'd prefer to keep this.
