### ISSUE TITLE
LATENCY command not working on latest version of Redis Sentinel

### ISSUE THREAD

**Issue by jkirkwood** [oliver006/redis_exporter#495]
I just upgraded from Redis 4.0.11 to Redis 6.2. I have exporters monitoring a few sentinel and server instances. The sentinel exporter keeps logging this error message on every scrape:

```
level=error msg="cmd LATENCY LATEST, err: ERR unknown command `LATENCY`, with args beginning with: `LATEST`, " 
```

Other than this error all other metrics are being scraped ok. I tried looking through the redis/sentinel docs to see if this command was removed/deprecated, but can't seem to find any reference to it.

The exporters monitoring the redis-server instances are not logging any errors.

I'm running the latest redis_exporter (1.17.1)

**Comment by oliver006** [comment]
Hmm, I'm following updates to the Sentinel closely as I'm not using them.

There is [another report](https://github.com/oliver006/redis_exporter/issues/124#issuecomment-786625450) of someone getting spammed by this log line so maybe we could either 1) provide a flag to disable probing for latency metrics or b) make the line Debugf or c) at least only log the error once.

No strong preference either way - thoughts? 

cc: @daquinoaldo - your issue is related

**Comment by daquinoaldo** [comment]
I would suggest to use a flag, but also logging it only once sounds good. Thank you!

**Comment by oliver006** [comment]
#505 should address this,LATENCY LATEST errors are now only logged once but every error is still logged with Debugf().

**Comment by daquinoaldo** [comment]
Thank you!
