### ISSUE TITLE
age label in redis_connected_clients_details spams prometheus server

### ISSUE THREAD

**Issue by h3isenbug** [oliver006/redis_exporter#496]
**Describe the problem**
age label of redis_connected_clients_details gets incremented every second and it makes a ton of metrics.

**What version of redis_exporter are you running?**
v1.17.1-amd64

**Comment by oliver006** [comment]
Ohhh, good catch. That's probably something we should replace with a timestamp instead. Something like `now() - age` so it'll stay constant and not constantly create new metrics.

If you want to submit a PR please go ahead and I can review it. Otherwise I'll try to get to it some time in the next couple of days/weeks.

**Comment by h3isenbug** [comment]
Yeah, that would do the trick. I'll submit my PR in 2 days tops.

**Comment by oliver006** [comment]
That'd be great, thanks!

**Comment by h3isenbug** [comment]
@oliver006 PR is ready, but the test environment seems to have problems with `latency` command.

**Comment by oliver006** [comment]
Closed by #534 - released as v1.25.0
