### ISSUE TITLE
Docker push action

### ISSUE THREAD

**Issue by trejjam** [oliver006/redis_exporter#771]
**Describe the problem**
Hello Oliver,
From time to time I hit issue that the docker container is missing for a new release. I propose to add Github actions which will automatically build and push the docker image for a new release. I can prepare PR for the action, I will only need you to create a secret key for that action.

**Additional context**
https://hub.docker.com/r/oliver006/redis_exporter/tags?page=1&name=v1.47
https://github.com/oliver006/redis_exporter/releases/tag/v1.47.0

**Comment by oliver006** [comment]
I hear you. Unfortunately, one of the tests broke (because I didn't have a dependecy pinned) so the release failed.
I'm looking into fixing this.
I'd love to make the CI/CD process more robust but moving the release process to Github Actions is a significant amount of work which I don't have the time for right now.
I know you offered help but there;'s also making sure that the manifests are created right, etc.
[I started some work on Github actions](https://github.com/oliver006/redis_exporter/pull/737) to at least run the tests there - if you want to piggy back on that just go ahead but right now I don't want to spend a ton of time on something that's working well (most of the time).

**Comment by oliver006** [comment]
Released https://github.com/oliver006/redis_exporter/releases/tag/v1.47.0
