### ISSUE TITLE
how to read redis_cpu_*_seconds_total ?

### ISSUE THREAD

**Issue by MosesMooreGameloft** [oliver006/redis_exporter#939]
**Describe the problem**
Getting weird numbers for what I expect is CPU-seconds-used counter

**What version of redis_exporter are you running?**
Redis Metrics Exporter v1.61.0    build date:     sha1: e9871c1465679cd3543953f57bd4d015bc73c990    Go: go1.22.4

**Running the exporter**
`/redis_exporter`

**Screenshots**
n/a

**Additional context**
I expect `rate(cpu_whatever_seconds_total[5m])` to return 1.0 for an average of 100% cpu use (one core) average over the last five minutes.  I'm seeing numbers between 0 and 300.0 for a cluster that has two nodes with 2 cores each -- 4.0 is the max I'm expecting, not 300.0.

What am I misunderstanding?

**Comment by oliver006** [comment]
No idea, pretty sure the number is passed through directly from whatever the Redis instance returns.
Try the redis docs for more information, maybe they explain how they calc the number.

**Comment by mozai** [comment]
Co-worker dived into it on the weekend: seems it's because there's a cluster behind the endpoint (surprise!) so it's acting very weird.  He believes some node-specific answers change because a different node answers each time, and it may be reporting the SUM of cpu_seconds across all nodes.  If I can get a HOWTO out of this, I'll come back and report.

**Comment by oliver006** [comment]
That's some great digging - thanks for the update!
